# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SubnetCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Subnet_Calculator(object):
    def setupUi(self, Subnet_Calculator):
        Subnet_Calculator.setObjectName("Subnet_Calculator")
        Subnet_Calculator.setEnabled(True)
        Subnet_Calculator.resize(678, 471)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Subnet_Calculator.sizePolicy().hasHeightForWidth())
        Subnet_Calculator.setSizePolicy(sizePolicy)
        Subnet_Calculator.setMinimumSize(QtCore.QSize(678, 471))
        Subnet_Calculator.setMaximumSize(QtCore.QSize(678, 471))
        Subnet_Calculator.setBaseSize(QtCore.QSize(678, 471))
        self.centralwidget = QtWidgets.QWidget(Subnet_Calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_network_information = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_network_information.setGeometry(QtCore.QRect(10, 20, 291, 131))
        self.groupBox_network_information.setObjectName("groupBox_network_information")
        self.label_nw_addr = QtWidgets.QLabel(self.groupBox_network_information)
        self.label_nw_addr.setGeometry(QtCore.QRect(20, 30, 91, 16))
        self.label_nw_addr.setObjectName("label_nw_addr")
        self.label_num_hosts_subnet = QtWidgets.QLabel(self.groupBox_network_information)
        self.label_num_hosts_subnet.setGeometry(QtCore.QRect(20, 60, 121, 16))
        self.label_num_hosts_subnet.setObjectName("label_num_hosts_subnet")
        self.label_subnet_sz = QtWidgets.QLabel(self.groupBox_network_information)
        self.label_subnet_sz.setGeometry(QtCore.QRect(20, 90, 121, 16))
        self.label_subnet_sz.setObjectName("label_subnet_sz")
        self.lineEdit_nw_addr = QtWidgets.QLineEdit(self.groupBox_network_information)
        self.lineEdit_nw_addr.setGeometry(QtCore.QRect(140, 30, 131, 20))
        self.lineEdit_nw_addr.setObjectName("lineEdit_nw_addr")
        self.lineEdit_num_hosts_subnet = QtWidgets.QLineEdit(self.groupBox_network_information)
        self.lineEdit_num_hosts_subnet.setGeometry(QtCore.QRect(140, 60, 131, 20))
        self.lineEdit_num_hosts_subnet.setObjectName("lineEdit_num_hosts_subnet")
        self.lineEdit_subnet_sz = QtWidgets.QLineEdit(self.groupBox_network_information)
        self.lineEdit_subnet_sz.setEnabled(False)
        self.lineEdit_subnet_sz.setGeometry(QtCore.QRect(140, 90, 91, 20))
        self.lineEdit_subnet_sz.setObjectName("lineEdit_subnet_sz")
        self.pushButton_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calculate.setGeometry(QtCore.QRect(580, 390, 75, 23))
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.groupBox_addr_info = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_addr_info.setGeometry(QtCore.QRect(313, 20, 351, 151))
        self.groupBox_addr_info.setObjectName("groupBox_addr_info")
        self.label_decimal_octets = QtWidgets.QLabel(self.groupBox_addr_info)
        self.label_decimal_octets.setGeometry(QtCore.QRect(8, 30, 91, 16))
        self.label_decimal_octets.setObjectName("label_decimal_octets")
        self.label_decimal_addr = QtWidgets.QLabel(self.groupBox_addr_info)
        self.label_decimal_addr.setGeometry(QtCore.QRect(8, 60, 91, 16))
        self.label_decimal_addr.setObjectName("label_decimal_addr")
        self.label_binary_octets = QtWidgets.QLabel(self.groupBox_addr_info)
        self.label_binary_octets.setGeometry(QtCore.QRect(8, 90, 91, 16))
        self.label_binary_octets.setObjectName("label_binary_octets")
        self.label_hex_octets = QtWidgets.QLabel(self.groupBox_addr_info)
        self.label_hex_octets.setGeometry(QtCore.QRect(8, 120, 91, 16))
        self.label_hex_octets.setObjectName("label_hex_octets")
        self.lineEdit_decimal_octets = QtWidgets.QLineEdit(self.groupBox_addr_info)
        self.lineEdit_decimal_octets.setEnabled(False)
        self.lineEdit_decimal_octets.setGeometry(QtCore.QRect(104, 30, 231, 20))
        self.lineEdit_decimal_octets.setObjectName("lineEdit_decimal_octets")
        self.lineEdit_decimal_addr = QtWidgets.QLineEdit(self.groupBox_addr_info)
        self.lineEdit_decimal_addr.setEnabled(False)
        self.lineEdit_decimal_addr.setGeometry(QtCore.QRect(104, 60, 231, 20))
        self.lineEdit_decimal_addr.setObjectName("lineEdit_decimal_addr")
        self.lineEdit_binary_octets = QtWidgets.QLineEdit(self.groupBox_addr_info)
        self.lineEdit_binary_octets.setEnabled(False)
        self.lineEdit_binary_octets.setGeometry(QtCore.QRect(104, 90, 231, 20))
        self.lineEdit_binary_octets.setObjectName("lineEdit_binary_octets")
        self.lineEdit_hex_octets = QtWidgets.QLineEdit(self.groupBox_addr_info)
        self.lineEdit_hex_octets.setEnabled(False)
        self.lineEdit_hex_octets.setGeometry(QtCore.QRect(104, 120, 231, 20))
        self.lineEdit_hex_octets.setObjectName("lineEdit_hex_octets")
        self.groupBox_Netmask_info = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Netmask_info.setGeometry(QtCore.QRect(313, 190, 351, 181))
        self.groupBox_Netmask_info.setObjectName("groupBox_Netmask_info")
        self.label_nw_class = QtWidgets.QLabel(self.groupBox_Netmask_info)
        self.label_nw_class.setGeometry(QtCore.QRect(8, 30, 91, 16))
        self.label_nw_class.setObjectName("label_nw_class")
        self.label_numberOf_IP_addr = QtWidgets.QLabel(self.groupBox_Netmask_info)
        self.label_numberOf_IP_addr.setGeometry(QtCore.QRect(8, 60, 91, 16))
        self.label_numberOf_IP_addr.setObjectName("label_numberOf_IP_addr")
        self.label_subnetmask = QtWidgets.QLabel(self.groupBox_Netmask_info)
        self.label_subnetmask.setGeometry(QtCore.QRect(8, 90, 91, 16))
        self.label_subnetmask.setObjectName("label_subnetmask")
        self.label_binary_mask = QtWidgets.QLabel(self.groupBox_Netmask_info)
        self.label_binary_mask.setGeometry(QtCore.QRect(8, 120, 91, 16))
        self.label_binary_mask.setObjectName("label_binary_mask")
        self.lineEdit_nw_class = QtWidgets.QLineEdit(self.groupBox_Netmask_info)
        self.lineEdit_nw_class.setEnabled(False)
        self.lineEdit_nw_class.setGeometry(QtCore.QRect(104, 30, 41, 20))
        self.lineEdit_nw_class.setObjectName("lineEdit_nw_class")
        self.lineEdit_numberOf_IP_addr = QtWidgets.QLineEdit(self.groupBox_Netmask_info)
        self.lineEdit_numberOf_IP_addr.setEnabled(False)
        self.lineEdit_numberOf_IP_addr.setGeometry(QtCore.QRect(104, 60, 71, 20))
        self.lineEdit_numberOf_IP_addr.setObjectName("lineEdit_numberOf_IP_addr")
        self.lineEdit_subnetmask = QtWidgets.QLineEdit(self.groupBox_Netmask_info)
        self.lineEdit_subnetmask.setEnabled(False)
        self.lineEdit_subnetmask.setGeometry(QtCore.QRect(104, 90, 231, 20))
        self.lineEdit_subnetmask.setObjectName("lineEdit_subnetmask")
        self.lineEdit_binary_mask = QtWidgets.QLineEdit(self.groupBox_Netmask_info)
        self.lineEdit_binary_mask.setEnabled(False)
        self.lineEdit_binary_mask.setGeometry(QtCore.QRect(104, 120, 231, 20))
        self.lineEdit_binary_mask.setObjectName("lineEdit_binary_mask")
        self.label_numberOf_subnets = QtWidgets.QLabel(self.groupBox_Netmask_info)
        self.label_numberOf_subnets.setGeometry(QtCore.QRect(8, 150, 91, 16))
        self.label_numberOf_subnets.setObjectName("label_numberOf_subnets")
        self.lineEdit_numberOf_subnets = QtWidgets.QLineEdit(self.groupBox_Netmask_info)
        self.lineEdit_numberOf_subnets.setEnabled(False)
        self.lineEdit_numberOf_subnets.setGeometry(QtCore.QRect(104, 150, 61, 20))
        self.lineEdit_numberOf_subnets.setObjectName("lineEdit_numberOf_subnets")
        self.groupBox_listOf_IP_ranges = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_listOf_IP_ranges.setGeometry(QtCore.QRect(10, 160, 291, 261))
        self.groupBox_listOf_IP_ranges.setObjectName("groupBox_listOf_IP_ranges")
        self.list_IP_ranges = QtWidgets.QListWidget(self.groupBox_listOf_IP_ranges)
        self.list_IP_ranges.setEnabled(True)
        self.list_IP_ranges.setGeometry(QtCore.QRect(10, 20, 271, 231))
        self.list_IP_ranges.setObjectName("list_IP_ranges")
        Subnet_Calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Subnet_Calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        Subnet_Calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Subnet_Calculator)
        self.statusbar.setObjectName("statusbar")
        Subnet_Calculator.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(Subnet_Calculator)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(Subnet_Calculator)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(Subnet_Calculator)
        self.actionExit.setObjectName("actionExit")
        self.actionCalculate = QtWidgets.QAction(Subnet_Calculator)
        self.actionCalculate.setObjectName("actionCalculate")
        self.actionClear = QtWidgets.QAction(Subnet_Calculator)
        self.actionClear.setObjectName("actionClear")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionCalculate)
        self.menuTools.addAction(self.actionClear)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(Subnet_Calculator)
        QtCore.QMetaObject.connectSlotsByName(Subnet_Calculator)

    def retranslateUi(self, Subnet_Calculator):
        _translate = QtCore.QCoreApplication.translate
        Subnet_Calculator.setWindowTitle(_translate("Subnet_Calculator", "Subnet Calculator"))
        self.groupBox_network_information.setTitle(_translate("Subnet_Calculator", "Network Information"))
        self.label_nw_addr.setText(_translate("Subnet_Calculator", "Network Address:"))
        self.label_num_hosts_subnet.setText(_translate("Subnet_Calculator", "# of  Hosts per Subnet:"))
        self.label_subnet_sz.setText(_translate("Subnet_Calculator", "Calculated Subnet Size:"))
        self.pushButton_calculate.setText(_translate("Subnet_Calculator", "Calculate"))
        self.groupBox_addr_info.setTitle(_translate("Subnet_Calculator", "Address Information"))
        self.label_decimal_octets.setText(_translate("Subnet_Calculator", "Decimal Octets :"))
        self.label_decimal_addr.setText(_translate("Subnet_Calculator", "Decimal Address :"))
        self.label_binary_octets.setText(_translate("Subnet_Calculator", "Binary Octets :"))
        self.label_hex_octets.setText(_translate("Subnet_Calculator", "Hex Octets :"))
        self.groupBox_Netmask_info.setTitle(_translate("Subnet_Calculator", "Netmask Information"))
        self.label_nw_class.setText(_translate("Subnet_Calculator", "Network Class:"))
        self.label_numberOf_IP_addr.setText(_translate("Subnet_Calculator", "# of IP Addresses:"))
        self.label_subnetmask.setText(_translate("Subnet_Calculator", "Subnet Mask:"))
        self.label_binary_mask.setText(_translate("Subnet_Calculator", "Binary Mask:"))
        self.label_numberOf_subnets.setText(_translate("Subnet_Calculator", "# of Subnets:"))
        self.groupBox_listOf_IP_ranges.setTitle(_translate("Subnet_Calculator", "List of  IP Ranges"))
        self.menuFile.setTitle(_translate("Subnet_Calculator", "File"))
        self.menuTools.setTitle(_translate("Subnet_Calculator", "Tools"))
        self.actionOpen.setText(_translate("Subnet_Calculator", "Open..."))
        self.actionSave_As.setText(_translate("Subnet_Calculator", "Save As..."))
        self.actionExit.setText(_translate("Subnet_Calculator", "Exit"))
        self.actionCalculate.setText(_translate("Subnet_Calculator", "Calculate"))
        self.actionClear.setText(_translate("Subnet_Calculator", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Subnet_Calculator = QtWidgets.QMainWindow()
    ui = Ui_Subnet_Calculator()
    ui.setupUi(Subnet_Calculator)
    Subnet_Calculator.show()
    sys.exit(app.exec_())

